# src/latest_ai_development/config/tasks.yaml
validate_transfer:
  description: >
    Validate the transfer request for {amount} ETH to {recipient} on Sepolia network.
    Check if:
    1. The recipient address is valid
    2. The amount is reasonable (not suspiciously high)
    3. The sender has sufficient balance
    4. The transaction complies with basic security rules
  expected_output: >
    A validation result with either approval or rejection, including detailed reason.
  agent: validator

execute_transfer:
  description: >
    Execute the transfer of {amount} ETH to {recipient} after validation.
    Record the transaction details and confirm completion.
  expected_output: >
    Transaction confirmation with transfer details and status.
  agent: transfer_agent
